/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hua_cmakerules_NativeAudio */
#include <android/log.h>

#define  LOG_TAG "NativeAudio_JNI"
#define ALOGV(...) __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
#define ALOGD(...) __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG,__VA_ARGS__)


#define ALOGM(fmt, ...)  __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG,\
                                             "[%s:%d]" fmt, __FUNCTION__, __LINE__,##__VA_ARGS__);


#ifndef _Included_com_hua_cmakerules_NativeAudio
#define _Included_com_hua_cmakerules_NativeAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    createBufferQueueAudioPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_createBufferQueueAudioPlayer
  (JNIEnv *, jclass);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    createAssetAudioPlayer
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hua_cmakerules_NativeAudio_createAssetAudioPlayer
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    setPlayingAssetAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_setPlayingAssetAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    createUriAudioPlayer
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hua_cmakerules_NativeAudio_createUriAudioPlayer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    setPlayingUriAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_setPlayingUriAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    setLoopingUriAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_setLoopingUriAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    setChannelMuteUriAudioPlayer
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_setChannelMuteUriAudioPlayer
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    setChannelSoloUriAudioPlayer
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_setChannelSoloUriAudioPlayer
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    getNumChannelsUriAudioPlayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hua_cmakerules_NativeAudio_getNumChannelsUriAudioPlayer
  (JNIEnv *, jclass);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    setVolumeUriAudioPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_setVolumeUriAudioPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    setMuteUriAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_setMuteUriAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    enableStereoPositionUriAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_enableStereoPositionUriAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    setStereoPositionUriAudioPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_setStereoPositionUriAudioPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    selectClip
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hua_cmakerules_NativeAudio_selectClip
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    enableReverb
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hua_cmakerules_NativeAudio_enableReverb
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    createAudioRecorder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_hua_cmakerules_NativeAudio_createAudioRecorder
  (JNIEnv *, jclass);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    startRecording
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_startRecording
  (JNIEnv *, jclass);

/*
 * Class:     com_hua_cmakerules_NativeAudio
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hua_cmakerules_NativeAudio_shutdown
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
